[build-system]
requires = [
    #
    # Avoid Cython 3.0.0 – too slow
    #
    "Cython>=0.29.32,<3.0.0",

    # For Python 3.8 on non-ARM, use NumPy 1.18.5 (Gensim minimum)
    "numpy==1.18.5; python_version == '3.8' and platform_machine != 'arm64' and platform_machine != 'aarch64'",

    # Use NumPy >= 1.19.0 on Windows ARM64 (avoid oldest-supported-numpy here)
    "numpy>=1.19.0; python_version > '3.8' and sys_platform == 'win32' and (platform_machine == 'arm64' or platform_machine == 'aarch64')",

    # Use oldest-supported-numpy elsewhere (Linux/macOS, x86_64)
    "oldest-supported-numpy; python_version > '3.8' and (platform_machine != 'arm64' and platform_machine != 'aarch64' or sys_platform != 'win32')",

    "setuptools",
    "wheel",
]
